/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datos;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Paredes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEljeirCuenta = new javax.swing.JButton();
        btnElejirArchivo = new javax.swing.JButton();
        rbCuentAhorro = new javax.swing.JRadioButton();
        rbCuentHipot = new javax.swing.JRadioButton();
        rbCuentPrest = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtArchivo = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEljeirCuenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnEljeirCuenta.setText("ELEJIR CUENTA");
        btnEljeirCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEljeirCuentaActionPerformed(evt);
            }
        });

        btnElejirArchivo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnElejirArchivo.setText("ELEJIR ARCHIVO");
        btnElejirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElejirArchivoActionPerformed(evt);
            }
        });

        rbCuentAhorro.setText("Cuneta Ahorro");
        rbCuentAhorro.setEnabled(false);
        rbCuentAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCuentAhorroActionPerformed(evt);
            }
        });

        rbCuentHipot.setText("Cuenta Hipoteca");
        rbCuentHipot.setEnabled(false);
        rbCuentHipot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCuentHipotActionPerformed(evt);
            }
        });

        rbCuentPrest.setText("Cuenta Prestamo");
        rbCuentPrest.setEnabled(false);
        rbCuentPrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCuentPrestActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");

        txtArchivo.setEditable(false);
        txtArchivo.setEnabled(false);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEljeirCuenta)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(rbCuentAhorro)
                        .addGap(18, 18, 18)
                        .addComponent(rbCuentHipot)
                        .addGap(18, 18, 18)
                        .addComponent(rbCuentPrest))
                    .addComponent(btnElejirArchivo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnElejirArchivo)
                .addGap(18, 18, 18)
                .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnEljeirCuenta)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCuentAhorro)
                    .addComponent(rbCuentHipot)
                    .addComponent(rbCuentPrest))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEljeirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEljeirCuentaActionPerformed
        rbCuentAhorro.setEnabled(true);
        rbCuentHipot.setEnabled(true);
        rbCuentPrest.setEnabled(true);
    }//GEN-LAST:event_btnEljeirCuentaActionPerformed

    private void btnElejirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElejirArchivoActionPerformed
        JFileChooser fc = new JFileChooser();
        int opc = fc.showOpenDialog(this);
        if (opc == JFileChooser.APPROVE_OPTION) {
            txtArchivo.setEnabled(true);
            txtArchivo.setText(fc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btnElejirArchivoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        int opc = JOptionPane.showConfirmDialog(this, "Seleccionó el archivo\n" + txtArchivo.getText() + "Desea continuar", "Elejir Archivo", JOptionPane.YES_NO_OPTION);
        if (opc == 0) {
            Banco.archivo = txtArchivo.getText();
        }else{
            btnElejirArchivoActionPerformed(evt);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void rbCuentAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCuentAhorroActionPerformed
        Cuenta c = Banco.buscarCuentaAhorro();
        JDCuentaAhorro ca = new JDCuentaAhorro(this, rootPaneCheckingEnabled);
        ca.setVisible(true);
        ca.setCa((CuentaAhorro) c);
    }//GEN-LAST:event_rbCuentAhorroActionPerformed

    private void rbCuentHipotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCuentHipotActionPerformed
        Cuenta c = Banco.buscarCuentaHipoteca();
        JDCuentaHipoteca ch = new JDCuentaHipoteca(this, rootPaneCheckingEnabled);
        ch.setVisible(true);
        ch.setCh((CuentaHipoteca) c);
    }//GEN-LAST:event_rbCuentHipotActionPerformed

    private void rbCuentPrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCuentPrestActionPerformed
        Cuenta c = Banco.buscarCuentaPrestamo();
        JDCuentaPrestamo cp = new JDCuentaPrestamo(this, rootPaneCheckingEnabled);
        cp.setVisible(true);
        cp.setCp((CuentaPrestamo) c);
    }//GEN-LAST:event_rbCuentPrestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnElejirArchivo;
    private javax.swing.JButton btnEljeirCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbCuentAhorro;
    private javax.swing.JRadioButton rbCuentHipot;
    private javax.swing.JRadioButton rbCuentPrest;
    private javax.swing.JTextField txtArchivo;
    // End of variables declaration//GEN-END:variables
}
